// ─── Portfolio Data ────────────────────────────────────────────────────────
// CDN base for images currently hosted on Webflow
const CDN = 'https://cdn.prod.website-files.com/67b6a9ac780b924c936f06b2/';

// Categories
const CAT = {
  PROJECTION: 'projection',
  INSTALLATION: 'installation',
  MOTION:       'motion',
  PERMANENT:    'permanent',
};

const PROJECTS = [
  {
    id: 'pier-86-projection-mapping',
    title: "Pier 86 Projection Mapping",
    client: "City of Seattle",
    year: 2025,
    category: CAT.PROJECTION,
    tags: ['Projection Mapping', 'TouchDesigner', 'Notch'],
    heroImage: CDN + '6943552e21cddcfed0b3b0cb_signal-2025-12-17-171234.jpeg',
    headline: "Seattle's largest projection mapping, celebrating the city's Native history on Pier 86.",
    description: "A landmark projection mapping installation on the Pier 86 building, one of Seattle's most visible facades, honoring the region's indigenous heritage through light and story.",
    featured: true,
    caseStudy: true,
    challenge: "The brief called for a historically sensitive, monumental light installation that could captivate thousands of viewers while honoring the indigenous communities of the Pacific Northwest. The building's irregular surface and surrounding light pollution required precision engineering.",
    solution: "Using Notch for real-time rendering and TouchDesigner for mapping calibration, we warped hand-illustrated imagery of local tribes, waterways, and traditional motifs to perfectly conform to the building's geometry. A custom projection rig was rigged and aligned over three nights before the public reveal.",
    outcome: "The installation drew tens of thousands of viewers over the run of the event and received widespread media coverage as the largest projection mapping Seattle had seen. Community leaders from several tribal nations participated in the opening ceremony.",
    technologies: ['Notch', 'TouchDesigner', 'Christie Projectors', 'Custom projection rigging'],
  },
  {
    id: 'intel-hq-lobby',
    title: "Intel HQ Lobby",
    client: "Intel",
    year: 2023,
    category: CAT.INSTALLATION,
    tags: ['Interactive Wall', 'Depth Camera', 'TouchDesigner', 'LED'],
    heroImage: CDN + '69438d2a7dfdfda5d143a086_IntelLobby.png',
    headline: "A fully reimagined corporate lobby featuring an interactive depth-camera wall and an inverted 360° cube ceiling.",
    description: "A permanent installation transforming Intel's headquarters lobby into an immersive, sensor-driven environment that reacts to every visitor who walks through the door.",
    featured: true,
    caseStudy: true,
    challenge: "Intel needed their headquarters lobby to embody their identity as a technology leader — something that would immediately communicate innovation to every visitor, partner, and employee. The solution had to run unattended, 24/7, without operator intervention.",
    solution: "We designed a dual-system installation: a large-format interactive video wall driven by Intel RealSense depth cameras that generates fluid particle simulations around visitors' silhouettes, paired with an inverted cube ceiling lined with LED panels rendering synchronized 360° environments. Both systems run on a hardened TouchDesigner architecture with automatic error recovery.",
    outcome: "The installation has run continuously since launch with zero downtime. It has been featured in Intel's own marketing materials and is shown to every prospective partner who visits the campus.",
    technologies: ['Intel RealSense D455', 'TouchDesigner', 'Custom LED panels', 'NVIDIA RTX workstation'],
  },
  {
    id: 'space-shuttle-mapping',
    title: "Space Shuttle Projection Mapping",
    client: "Museum of Flight / NASA",
    year: 2022,
    category: CAT.PROJECTION,
    tags: ['Projection Mapping', 'Notch', 'Large Format'],
    heroImage: CDN + '694340bfd24579622d0f88f5_spaceshuttle.jpeg',
    headline: "Projection mapping the NASA Space Shuttle at the Museum of Flight — a 122-foot canvas.",
    description: "The full fuselage of the Space Shuttle Trainer at Seattle's Museum of Flight became a canvas for a large-scale projection mapping narrative celebrating humanity's reach into space.",
    featured: true,
    caseStudy: true,
    challenge: "Mapping a curved, 122-foot spacecraft in a live museum environment with ambient lighting and visitor foot traffic required precise geometric calibration and a story that felt worthy of the subject matter.",
    solution: "A multi-projector array was configured using Notch's real-time 3D mapping tools, allowing for fast on-site adjustments as conditions changed. The narrative was authored as a series of acts — launch, orbit, re-entry, return — each with distinct visual language and original sound design.",
    outcome: "The event sold out within hours of announcement and generated significant press coverage. The Museum of Flight has since used the mapping as a flagship example in their event marketing.",
    technologies: ['Notch', 'Multi-projector array', 'Original sound design', '3D geometric calibration'],
  },
  {
    id: 'mariposa-chandelier',
    title: "Mariposa Chandelier",
    client: "Cultural Commission",
    year: 2021,
    category: CAT.PERMANENT,
    tags: ['LED Fabrication', 'Spatial Audio', 'Unity', 'Custom Hardware'],
    heroImage: CDN + '67b780eb3e3561a4c9292a87_chandelier1.jpg',
    headline: "A 4-story interactive LED chandelier with 120 hand-built lamps, narrating a Mayan folktale through light and spatial sound.",
    description: "A permanent public artwork standing four stories tall, comprising 120 custom-fabricated luminous elements synchronized to an original spatial audio composition that tells the story of Mariposa, a Mayan tale of transformation.",
    featured: true,
    caseStudy: true,
    challenge: "The commission required a permanent artwork that could endure years of continuous operation in a high-traffic public space, while remaining narratively rich and responsive to visitors. Custom fabrication at architectural scale was mandatory.",
    solution: "Each of the 120 lamp elements was individually designed, fabricated, and wired with addressable LED cores and diffusion materials selected for longevity. Unity drove the lighting choreography, synced to a 40-speaker spatial audio system. The narrative plays on a timed cycle that visitors can interrupt with proximity sensors.",
    outcome: "The piece has been in continuous operation since installation. It anchors the building's central atrium and has become its most photographed feature, appearing regularly in the institution's promotional materials.",
    technologies: ['Custom LED fabrication', 'Unity', '40-channel spatial audio', 'Proximity sensors', 'Addressable LED'],
  },
  {
    id: 'intel-ces-keynote',
    title: "Intel CES Keynote Performance",
    client: "Intel",
    year: 2020,
    category: CAT.MOTION,
    tags: ['Real-Time 3D', 'Depth Camera', 'Unreal Engine', 'Live Event'],
    heroImage: CDN + '67b77d16cb2cfc0eeff8da50_mg3ZgOY0.png',
    headline: "Real-time 3D visualization of trampoline acrobats at CES, showcasing Intel RealSense depth camera technology live on stage.",
    description: "A live keynote performance in which trampoline acrobats were captured in real-time by a array of Intel RealSense cameras and rendered as volumetric 3D figures on massive screens behind them — all with zero latency.",
    featured: true,
    caseStudy: true,
    challenge: "Intel needed a live, onstage demonstration of their RealSense depth sensing technology that would be immediately understandable to a non-technical audience of tens of thousands, with zero tolerance for latency or failure in front of a live broadcast.",
    solution: "A custom multi-camera RealSense rig captured performers from multiple angles simultaneously, with a bespoke Unreal Engine pipeline fusing the point cloud data into a clean volumetric render in real time. Rehearsals over three days validated the zero-latency pipeline before the live show.",
    outcome: "The demonstration became the highlight moment of Intel's CES keynote, appearing in press coverage across dozens of technology publications. It directly drove commercial interest in the RealSense product line.",
    technologies: ['Intel RealSense D435', 'Unreal Engine', 'Custom point cloud fusion', 'NVIDIA RTX'],
  },
  {
    id: 'ring-of-light',
    title: "Ring of Light",
    client: "Stadium of Light / City of Sunderland",
    year: 2023,
    category: CAT.PERMANENT,
    tags: ['Smart City', 'Data Visualization', 'LED Sculpture', 'Custom Fabrication'],
    heroImage: CDN + '69438a1b36396888405b59e5_RingOfLight4.png',
    headline: "A permanent smart city sculpture outside Sunderland's Stadium of Light that visualizes live urban data as shifting patterns of light.",
    description: "An architectural-scale LED ring sculpture installed as a permanent landmark outside Sunderland's Stadium of Light, continuously visualizing live smart city data — foot traffic, energy usage, event activity — as abstract light patterns.",
    featured: true,
    caseStudy: false,
    challenge: "The city needed a landmark artwork that could serve as both a civic symbol and a functional visualization of their smart city data infrastructure. It had to operate reliably in the harsh coastal climate of northeast England.",
    solution: "A structural ring in weatherproof steel was fitted with purpose-designed LED strips and driven by a custom data pipeline pulling from the city's smart infrastructure APIs. The visual language was designed to be intuitively readable without requiring any explanation.",
    outcome: "The piece has become one of the most recognized public artworks in Sunderland and is featured prominently in the city's smart city initiative communications.",
    technologies: ['Custom weatherproof LED', 'Smart city API integration', 'TouchDesigner', 'Structural steel fabrication'],
  },
  {
    id: 'coachella-republic-records',
    title: "Coachella — Republic Records VIP",
    client: "Republic Records / Phantogram",
    year: 2019,
    category: CAT.MOTION,
    tags: ['Real-Time Visuals', 'TouchDesigner', 'Live Performance'],
    heroImage: CDN + '67b77fa488b7edd898cd449a_Screenshot%202025-02-20%20at%2011.14.25%E2%80%AFAM.png',
    headline: "Real-time generative visuals for Republic Records and Phantogram at their Coachella VIP party.",
    description: "A fully live, reactive visual environment designed for the Republic Records VIP experience at Coachella, driven by audio analysis of the live set in real time.",
    featured: false,
    caseStudy: false,
    challenge: null,
    solution: null,
    outcome: null,
    technologies: ['TouchDesigner', 'Audio-reactive', 'Real-time rendering'],
  },
  {
    id: 'houston-architectural-model',
    title: "Houston Architectural Model",
    client: "City of Houston",
    year: 2022,
    category: CAT.INSTALLATION,
    tags: ['Interactive Model', 'TouchDesigner', 'Custom Hardware'],
    heroImage: CDN + '69434f63cb3efe485cccbbb1_HoustonProject2.png',
    headline: "An interactive physical architectural model of Houston with a controller that illuminates individual buildings in real time.",
    description: "A large-scale physical model of Houston's urban core with embedded LED elements allowing visitors to select and illuminate individual buildings and neighborhoods via a custom interface.",
    featured: false,
    caseStudy: false,
    challenge: null,
    solution: null,
    outcome: null,
    technologies: ['TouchDesigner', 'Custom controller hardware', 'Addressable LED', 'Physical model fabrication'],
  },
  {
    id: 'modular-nights',
    title: "Modular Nights",
    client: "Modular Seattle / Substation",
    year: 2023,
    category: CAT.MOTION,
    tags: ['Real-Time VFX', 'Camera-Based', 'Live Event', 'TouchDesigner'],
    heroImage: CDN + '69434f0bc477db961a84a3b5_ModularNights2.png',
    headline: "Real-time camera-based visual effects for Modular Seattle's performances at Substation.",
    description: "Live visual effects system capturing performers in real time and applying generative effects layered over their silhouettes for modular synthesizer concerts.",
    featured: false,
    caseStudy: false,
    challenge: null,
    solution: null,
    outcome: null,
    technologies: ['TouchDesigner', 'Camera tracking', 'Generative VFX'],
  },
  {
    id: 'luminous-flower',
    title: "Luminous Flower",
    client: "Portland Winter Light Festival",
    year: 2022,
    category: CAT.PERMANENT,
    tags: ['LED Sculpture', 'Custom Fabrication', 'Outdoor'],
    heroImage: CDN + '67b77c49e113ad7b007a1d75_Screenshot%202025-02-20%20at%2011.02.20%E2%80%AFAM.png',
    headline: "A glowing LED flower sculpture created for the Portland Winter Light Festival.",
    description: "A large-scale luminous flower sculpture with programmed light patterns designed for the Portland Winter Light Festival, collaborating with Joshua Rauch.",
    featured: false,
    caseStudy: false,
    challenge: null,
    solution: null,
    outcome: null,
    technologies: ['Custom LED fabrication', 'Arduino', 'Outdoor-rated materials'],
  },
  {
    id: 'ghostly-visions',
    title: "Ghostly Visions",
    client: "Pacific Science Center",
    year: 2023,
    category: CAT.MOTION,
    tags: ['Real-Time VFX', 'AR', 'Event Activation'],
    heroImage: CDN + '67b76e6e5d089b469909ff8d_Screenshot%202025-02-19%20at%203.45.38%E2%80%AFPM.png',
    headline: "Real-time visual effects enhancing guest costumes for Pacific Science Center's Halloween event.",
    description: "An interactive experience booth where guests stepped in front of cameras to have their Halloween costumes enhanced with real-time supernatural visual effects.",
    featured: false,
    caseStudy: false,
    challenge: null,
    solution: null,
    outcome: null,
    technologies: ['TouchDesigner', 'Camera-based AR', 'Real-time compositing'],
  },
  {
    id: 'projection-mapped-people',
    title: "Projection Mapped People",
    client: "Self-Initiated",
    year: 2022,
    category: CAT.MOTION,
    tags: ['Depth Camera', 'Projection Mapping', 'R&D'],
    heroImage: CDN + '67b77585186d5b53dfe6ad44_Screenshot%202025-02-19%20at%203.50.26%E2%80%AFPM.png',
    headline: "Depth cameras and virtual backgrounds create seamless projection-mapped effects on live performers.",
    description: "An R&D exploration using Intel RealSense depth cameras to track and project-map directly onto people in real time, creating illusions of virtual costumes and environments.",
    featured: false,
    caseStudy: false,
    challenge: null,
    solution: null,
    outcome: null,
    technologies: ['Intel RealSense', 'TouchDesigner', 'Projection mapping'],
  },
  {
    id: 'crystal-mountain-installation',
    title: "Crystal Mountain Installation",
    client: "Crystal Mountain Resort",
    year: 2023,
    category: CAT.PERMANENT,
    tags: ['Outdoor Sculpture', 'Custom Fabrication', 'Summit Installation'],
    heroImage: CDN + '69434c99d76ee473392f89b6_HighresScreenshot00030.png',
    headline: "A proposed permanent outdoor installation at the summit of Crystal Mountain, designed to endure alpine conditions year-round.",
    description: "A permanent outdoor installation concept designed to mark the summit of Crystal Mountain with light and structure that responds to atmospheric conditions.",
    featured: false,
    caseStudy: false,
    challenge: null,
    solution: null,
    outcome: null,
    technologies: ['Custom fabrication', 'Weatherproof LED', 'Structural engineering'],
  },
  {
    id: 'hololens-data-visualization',
    title: "HoloLens Data Visualization",
    client: "Microsoft",
    year: 2018,
    category: CAT.MOTION,
    tags: ['HoloLens', 'Mixed Reality', 'Keynote', 'Data Visualization'],
    heroImage: CDN + '67b7815063d3a5968cc51877_Screenshot%202025-02-20%20at%2011.22.55%E2%80%AFAM.png',
    headline: "Mixed reality data visualization for a Microsoft keynote, using HoloLens to render 3D data in physical space.",
    description: "Custom mixed reality visualizations authored for a Microsoft keynote presentation, allowing a presenter to interact with 3D data objects overlaid on the physical stage.",
    featured: false,
    caseStudy: false,
    challenge: null,
    solution: null,
    outcome: null,
    technologies: ['Microsoft HoloLens', 'Unity', '3D data visualization'],
  },
  {
    id: 'touch-tunnel',
    title: "Touch Tunnel",
    client: "AIGA",
    year: 2017,
    category: CAT.INSTALLATION,
    tags: ['Touch Sensors', 'Interactive Fabric', 'LED', 'Custom Hardware'],
    heroImage: CDN + '67b77d595c7f4acaa99604a8_8106122_orig.png',
    headline: "An interactive fabric tunnel at an AIGA event where guests trigger waves of light through touch.",
    description: "A tunnel-shaped installation covered in conductive fabric, where each touch from a passerby propagated waves of color and light through the structure.",
    featured: false,
    caseStudy: false,
    challenge: null,
    solution: null,
    outcome: null,
    technologies: ['Conductive fabric', 'Addressable LED', 'Custom touch sensors', 'Arduino'],
  },
  {
    id: 'childrens-hospital-donor-wall',
    title: "Children's Hospital Donor Wall",
    client: "Boston Children's Hospital",
    year: 2021,
    category: CAT.INSTALLATION,
    tags: ['Interactive Display', 'Donor Recognition', 'Custom UI'],
    heroImage: CDN + '67b77e0086cac9637d9c42e4_still1.png',
    headline: "An interactive donor recognition wall prototype for Boston Children's Hospital.",
    description: "An interactive prototype for Boston Children's Hospital's donor recognition program, allowing visitors to explore stories of donors through touch and gesture.",
    featured: false,
    caseStudy: false,
    challenge: null,
    solution: null,
    outcome: null,
    technologies: ['TouchDesigner', 'Touch screen integration', 'Custom UI design'],
  },
  {
    id: 'iluminate-dance-suits',
    title: "iLuminate Dance Suits",
    client: "iLuminate / America's Got Talent",
    year: 2016,
    category: CAT.INSTALLATION,
    tags: ['Wearable LED', 'Custom Hardware', 'Choreography Sync', 'Live Performance'],
    heroImage: CDN + '67b78347d118f5d32a2e43e1_iluminate4.jpg',
    headline: "Choreographable LED dance suits synchronized to music, featured on America's Got Talent.",
    description: "Custom-engineered wearable LED suits for the iLuminate dance company, with choreography-driven lighting synchronized wirelessly to musical cues in real time.",
    featured: false,
    caseStudy: false,
    challenge: null,
    solution: null,
    outcome: null,
    technologies: ['Wearable LED', 'Wireless sync', 'Custom firmware', 'Flexible electronics'],
  },
  {
    id: 'steve-aoki-paul-oakenfold',
    title: "Visuals for Steve Aoki & Paul Oakenfold",
    client: "Steve Aoki / Paul Oakenfold",
    year: 2018,
    category: CAT.MOTION,
    tags: ['Biometric', 'Wearable Data', 'Real-Time Visuals', 'Unreal Engine'],
    heroImage: CDN + '67b781c28ee037ada7dd2f34_1702.PNG',
    headline: "Real-time visuals driven by biometric and motion data from wearable bracelets worn by Steve Aoki and Paul Oakenfold.",
    description: "Live performance visuals that responded in real time to biometric and motion data streamed from custom wearable bracelets worn by the artists during their sets.",
    featured: false,
    caseStudy: false,
    challenge: null,
    solution: null,
    outcome: null,
    technologies: ['Custom wearable sensors', 'Unreal Engine', 'Real-time data streaming', 'Biometric processing'],
  },
];

// Category display names
const CATEGORY_LABELS = {
  [CAT.PROJECTION]:   'Projection Mapping',
  [CAT.INSTALLATION]: 'Interactive Installations',
  [CAT.MOTION]:       'Motion & Live Visuals',
  [CAT.PERMANENT]:    'Permanent Installations',
};

// Export for use in other scripts
if (typeof module !== 'undefined') {
  module.exports = { PROJECTS, CAT, CATEGORY_LABELS };
}
