// ─── Portfolio Data ────────────────────────────────────────────────────────
// CDN base for images currently hosted on Webflow
const CDN = 'https://cdn.prod.website-files.com/67b6a9ac780b924c936f06b2/';

// Categories
const CAT = {
  PROJECTION: 'projection',
  INSTALLATION: 'installation',
  MOTION:       'motion',
  PERMANENT:    'permanent',
};

const PROJECTS = [
  // ── User's ordered list ──────────────────────────────────────────────────
  {
    id: 'ring-of-light',
    title: "Ring of Light",
    client: "Stadium of Light / City of Sunderland",
    year: 2023,
    clientType: 'city',
    category: CAT.PERMANENT,
    tags: ['Smart City', 'Data Visualization', 'LED Sculpture', 'Custom Fabrication'],
    heroImage: CDN + '69438a1b36396888405b59e5_RingOfLight4.png',
    headline: "A permanent smart city sculpture outside Sunderland's Stadium of Light that visualizes live urban data as shifting patterns of light.",
    description: "An architectural-scale LED ring sculpture installed as a permanent landmark outside Sunderland's Stadium of Light, continuously visualizing live smart city data — foot traffic, energy usage, event activity — as abstract light patterns.",
    featured: true,
    caseStudy: true,
    challenge: "The city needed a landmark artwork that could serve as both a civic symbol and a functional visualization of their smart city data infrastructure. It had to operate reliably in the harsh coastal climate of northeast England.",
    solution: "A structural ring in weatherproof steel was fitted with purpose-designed LED strips and driven by a custom data pipeline pulling from the city's smart infrastructure APIs. The visual language was designed to be intuitively readable without requiring any explanation.",
    outcome: "The piece has become one of the most recognized public artworks in Sunderland and is featured prominently in the city's smart city initiative communications.",
    technologies: ['Custom weatherproof LED', 'Smart city API integration', 'TouchDesigner', 'Structural steel fabrication'],
  },
  {
    id: 'intel-ces-keynote',
    title: "Intel CES Keynote Performance",
    client: "Intel",
    year: 2020,
    clientType: 'tech',
    category: CAT.MOTION,
    tags: ['Real-Time 3D', 'Depth Camera', 'Unity VFX Graph', 'Live Event'],
    heroImage: CDN + '67b77d16cb2cfc0eeff8da50_mg3ZgOY0.png',
    headline: "Real-time volumetric visualization of trampoline acrobats on an 85'×40' LED wall at CES — showcasing Intel RealSense live on stage in front of a global broadcast audience.",
    description: "A live keynote performance in which trampoline acrobats were captured in real-time by a multi-camera Intel RealSense array and rendered as volumetric figures across an 85'×40' LED wall — zero latency, zero margin for error, in front of tens of thousands with Brian Krzanich on stage.",
    featured: true,
    caseStudy: true,
    challenge: "Intel needed a live, onstage demonstration of their RealSense depth sensing technology that would be immediately understandable to a non-technical audience of tens of thousands, with zero tolerance for latency or failure in front of a live broadcast. An early Optitrack motion capture approach proved unreliable under live show conditions.",
    solution: "The team pivoted from motion capture suits to raw point cloud data — a multi-camera RealSense array fed live depth data into a Unity VFX Graph pipeline with synchronized Notch outputs displayed across the 85'×40' LED wall. LED floor animations were coordinated with performer tracking in real time. Three days of rehearsals validated the zero-latency pipeline before the live show. Collaborators: Zero Gravity Arts, All of it Now.",
    outcome: "Forbes described Intel's CES keynote as featuring 'the most visually rich performance ... ever seen at a tech show — colorful, complex and stunning.' The demonstration became the highlight moment of the keynote, appearing in press coverage across dozens of technology publications and directly driving commercial interest in the RealSense product line.",
    technologies: ['Intel RealSense D435', 'Unity VFX Graph', 'Notch', 'Point cloud data pipeline', 'Optitrack (initial prototype)'],
  },
  {
    id: 'mariposa-chandelier',
    title: "Mariposa Chandelier",
    client: "Cultural Commission",
    year: 2021,
    clientType: 'institution',
    category: CAT.PERMANENT,
    tags: ['LED Fabrication', 'Spatial Audio', 'Unity', 'Custom Hardware'],
    heroImage: CDN + '67b780eb3e3561a4c9292a87_chandelier1.jpg',
    headline: "A 4-story interactive LED chandelier in Portland, OR — 120 hand-built lamps, each with 13 individually controllable LEDs and 12 acrylic light strands, narrating 'The Chocolate Tree' Mayan folktale through light and spatial sound.",
    description: "A permanent public artwork in Portland, OR, standing four stories tall — 120 custom-fabricated lamps (13 individually controllable LEDs and 12 acrylic light-diffusion strands each), synchronized to a multi-channel audio composition telling 'The Chocolate Tree,' a Mayan folktale. Commissioned by architect Rezan Prananta to make the building's staircase more compelling than its elevators.",
    featured: true,
    caseStudy: true,
    challenge: "Architect Rezan Prananta commissioned an interactive artwork to draw people to the building's staircase — the piece needed to be narratively rich, architecturally integrated at four-story scale, and built for continuous unattended operation in a high-traffic public space. Every lamp had to be individually fabricated, wired, and tuned.",
    solution: "Each of the 120 lamps was custom-fabricated by ADX Portland, with 13 individually controllable LEDs and 12 strands of acrylic for light diffusion. Unity drove the lighting choreography, synced to a multi-channel spatial audio system tuned on-site for the stairwell acoustics. Visitor interactivity was embedded into the elevator call buttons — each fitted with a ring light that triggers narrative sequences, encouraging the choice of stairs over elevator. Collaborators: Shears Adkins Rockmore (Architecture), ADX Portland (Fabrication), We Are PDX (Media).",
    outcome: "The piece has been in continuous operation since installation. It anchors the building's central atrium and has become its most photographed feature, appearing regularly in the institution's promotional materials.",
    technologies: ['Custom LED fabrication (ADX Portland)', 'Unity', 'Multi-channel spatial audio', 'Elevator button interactivity', '12-strand acrylic light diffusion'],
  },
  {
    id: 'ghostly-visions',
    title: "Ghostly Visions",
    client: "Pacific Science Center",
    year: 2023,
    clientType: 'institution',
    category: CAT.MOTION,
    tags: ['Real-Time VFX', 'AR', 'Event Activation'],
    heroImage: CDN + '67b76e6e5d089b469909ff8d_Screenshot%202025-02-19%20at%203.45.38%E2%80%AFPM.png',
    headline: "Real-time visual effects enhancing guest costumes for Pacific Science Center's Halloween event.",
    description: "An interactive experience booth where guests stepped in front of cameras to have their Halloween costumes enhanced with real-time supernatural visual effects.",
    featured: false,
    caseStudy: true,
    challenge: null,
    solution: null,
    outcome: null,
    technologies: ['TouchDesigner', 'Camera-based AR', 'Real-time compositing'],
  },
  {
    id: 'luminous-flower',
    title: "Luminous Flower",
    client: "Portland Winter Light Festival",
    year: 2022,
    clientType: 'festival',
    category: CAT.PERMANENT,
    tags: ['LED Sculpture', 'Custom Fabrication', 'Outdoor'],
    heroImage: CDN + '67b77c49e113ad7b007a1d75_Screenshot%202025-02-20%20at%2011.02.20%E2%80%AFAM.png',
    headline: "A glowing LED flower sculpture created for the Portland Winter Light Festival.",
    description: "A large-scale luminous flower sculpture with programmed light patterns designed for the Portland Winter Light Festival, collaborating with Joshua Rauch.",
    featured: false,
    caseStudy: true,
    challenge: null,
    solution: null,
    outcome: null,
    technologies: ['Custom LED fabrication', 'Arduino', 'Outdoor-rated materials'],
  },
  {
    id: 'intel-hq-lobby',
    title: "Intel HQ Lobby",
    client: "Intel",
    year: 2023,
    clientType: 'tech',
    category: CAT.INSTALLATION,
    tags: ['Interactive Wall', 'Depth Camera', 'TouchDesigner', 'LED'],
    heroImage: CDN + '69438d2a7dfdfda5d143a086_IntelLobby.png',
    headline: "A fully reimagined corporate lobby at Intel's Santa Clara HQ — interactive depth-camera Brand Story Wall, inverted 360° LED ceiling skylight, previewed in VR before a single panel was installed.",
    description: "A permanent installation transforming Intel's Santa Clara headquarters lobby into an immersive, sensor-driven environment — designed with All of it Now and Prefrontal Cortex — that reacts to every visitor who walks through the door, every hour of every day.",
    featured: true,
    caseStudy: true,
    challenge: "Intel needed their headquarters lobby to embody their identity as a technology leader — something that would immediately communicate innovation to every visitor, partner, and employee. The solution had to run unattended, 24/7, without operator intervention. Getting client sign-off on an installation of this scale — before construction — required a completely different approach.",
    solution: "Working with All of it Now and Prefrontal Cortex, we built a VR prototype that streamed live RealSense depth data into a virtual model of the lobby, letting Intel visualize the finished installation before anything was fabricated. The final build comprised a large-format Brand Story Wall driven by RealSense cameras generating particle simulations around visitors' silhouettes, paired with an inverted LED ceiling skylight rendering synchronized 360° environments — both on a hardened architecture with automatic error recovery.",
    outcome: "The installation has run continuously since launch with zero downtime. Hexagon Misfit provided 24/7 on-call support for six months post-completion before full handoff to Intel's internal team. The installation has been featured in Intel's own marketing materials and is shown to every prospective partner who visits the campus.",
    technologies: ['Intel RealSense D455', 'TouchDesigner', 'Custom LED panels', 'VR prototype (pre-build visualization)', 'NVIDIA RTX workstation'],
  },
  {
    id: 'modular-nights',
    title: "Modular Nights",
    client: "Modular Seattle / Substation",
    year: 2023,
    clientType: 'music',
    category: CAT.MOTION,
    tags: ['Real-Time VFX', 'Camera-Based', 'Live Event', 'TouchDesigner'],
    heroImage: CDN + '69434f0bc477db961a84a3b5_ModularNights2.png',
    headline: "Real-time camera-based visual effects for Modular Seattle's performances at Substation.",
    description: "Live visual effects system capturing performers in real time and applying generative effects layered over their silhouettes for modular synthesizer concerts.",
    featured: false,
    caseStudy: true,
    challenge: null,
    solution: null,
    outcome: null,
    technologies: ['TouchDesigner', 'Camera tracking', 'Generative VFX'],
  },
  {
    id: 'houston-architectural-model',
    title: "Houston Architectural Model",
    client: "City of Houston",
    year: 2022,
    clientType: 'city',
    category: CAT.INSTALLATION,
    tags: ['Interactive Model', 'TouchDesigner', 'Custom Hardware'],
    heroImage: CDN + '69434f63cb3efe485cccbbb1_HoustonProject2.png',
    headline: "An interactive physical architectural model of Houston with a controller that illuminates individual buildings in real time.",
    description: "A large-scale physical model of Houston's urban core with embedded LED elements allowing visitors to select and illuminate individual buildings and neighborhoods via a custom interface.",
    featured: false,
    caseStudy: true,
    challenge: null,
    solution: null,
    outcome: null,
    technologies: ['TouchDesigner', 'Custom controller hardware', 'Addressable LED', 'Physical model fabrication'],
  },
  {
    id: 'coachella-republic-records',
    title: "Coachella — Republic Records VIP",
    client: "Republic Records / Phantogram",
    year: 2019,
    clientType: 'music',
    category: CAT.MOTION,
    tags: ['Real-Time Visuals', 'TouchDesigner', 'Live Performance'],
    heroImage: CDN + '67b77fa488b7edd898cd449a_Screenshot%202025-02-20%20at%2011.14.25%E2%80%AFAM.png',
    headline: "Real-time generative visuals for Republic Records and Phantogram at their Coachella VIP party.",
    description: "A fully live, reactive visual environment designed for the Republic Records VIP experience at Coachella, driven by audio analysis of the live set in real time.",
    featured: false,
    caseStudy: true,
    challenge: null,
    solution: null,
    outcome: null,
    technologies: ['TouchDesigner', 'Audio-reactive', 'Real-time rendering'],
  },
  {
    id: 'iluminate-dance-suits',
    title: "iLuminate Dance Suits",
    client: "iLuminate / America's Got Talent",
    year: 2016,
    clientType: 'music',
    category: CAT.INSTALLATION,
    tags: ['Wearable LED', 'Custom Hardware', 'Choreography Sync', 'Live Performance'],
    heroImage: CDN + '67b78347d118f5d32a2e43e1_iluminate4.jpg',
    headline: "Choreographable Electro-Luminescent wire dance suits worn by the Black Eyed Peas, Christina Aguilera, and Britney Spears — and featured on America's Got Talent.",
    description: "Custom-engineered EL-wire dance suits for iLuminate (founded by Miral Kotb) — 8 individually addressable light strands per suit, WiFi-controlled via Processing with unique suit IDs. Prototyped at SparkFun Electronics; iLuminate continued performing in refined versions of these suits for 10+ years after launch.",
    featured: false,
    caseStudy: true,
    challenge: null,
    solution: null,
    outcome: null,
    technologies: ['Electro-Luminescent (EL) Wire', 'WiFi control via Processing', 'Custom firmware', '8 addressable strands/suit'],
  },
  {
    id: 'touch-tunnel',
    title: "Touch Tunnel",
    client: "AIGA",
    year: 2017,
    clientType: 'festival',
    category: CAT.INSTALLATION,
    tags: ['Touch Sensors', 'Interactive Fabric', 'LED', 'Custom Hardware'],
    heroImage: CDN + '67b77d595c7f4acaa99604a8_8106122_orig.png',
    headline: "An interactive fabric tunnel at an AIGA event where guests trigger waves of light through touch.",
    description: "A tunnel-shaped installation covered in conductive fabric, where each touch from a passerby propagated waves of color and light through the structure.",
    featured: false,
    caseStudy: true,
    challenge: null,
    solution: null,
    outcome: null,
    technologies: ['Conductive fabric', 'Addressable LED', 'Custom touch sensors', 'Arduino'],
  },
  {
    id: 'crystal-mountain-installation',
    title: "Crystal Mountain Installation",
    client: "Crystal Mountain Resort",
    year: 2023,
    clientType: 'festival',
    category: CAT.PERMANENT,
    tags: ['Outdoor Sculpture', 'Custom Fabrication', 'Summit Installation'],
    heroImage: CDN + '69434c99d76ee473392f89b6_HighresScreenshot00030.png',
    headline: "A proposed permanent outdoor installation at the summit of Crystal Mountain, designed to endure alpine conditions year-round.",
    description: "A permanent outdoor installation concept designed to mark the summit of Crystal Mountain with light and structure that responds to atmospheric conditions.",
    featured: false,
    caseStudy: true,
    challenge: null,
    solution: null,
    outcome: null,
    technologies: ['Custom fabrication', 'Weatherproof LED', 'Structural engineering'],
  },
  // ── Appended (not in user's ordered list) ───────────────────────────────
  {
    id: 'pier-86-projection-mapping',
    title: "Pier 86 Projection Mapping",
    client: "City of Seattle",
    year: 2025,
    clientType: 'city',
    category: CAT.PROJECTION,
    tags: ['Projection Mapping', 'TouchDesigner', 'Notch'],
    heroImage: CDN + '6943552e21cddcfed0b3b0cb_signal-2025-12-17-171234.jpeg',
    headline: "Seattle's largest projection mapping, celebrating the city's Native history on Pier 86.",
    description: "A landmark projection mapping installation on the Pier 86 building, one of Seattle's most visible facades, honoring the region's indigenous heritage through light and story.",
    featured: true,
    caseStudy: true,
    challenge: "The brief called for a historically sensitive, monumental light installation that could captivate thousands of viewers while honoring the indigenous communities of the Pacific Northwest. The building's irregular surface and surrounding light pollution required precision engineering.",
    solution: "Using Notch for real-time rendering and TouchDesigner for mapping calibration, we warped hand-illustrated imagery of local tribes, waterways, and traditional motifs to perfectly conform to the building's geometry. A custom projection rig was rigged and aligned over three nights before the public reveal.",
    outcome: "The installation drew tens of thousands of viewers over the run of the event and received widespread media coverage as the largest projection mapping Seattle had seen. Community leaders from several tribal nations participated in the opening ceremony.",
    technologies: ['Notch', 'TouchDesigner', 'Christie Projectors', 'Custom projection rigging'],
  },
  {
    id: 'space-shuttle-mapping',
    title: "Space Shuttle Projection Mapping",
    client: "Museum of Flight / NASA",
    year: 2022,
    clientType: 'institution',
    category: CAT.PROJECTION,
    tags: ['Projection Mapping', 'Notch', 'Large Format'],
    heroImage: CDN + '694340bfd24579622d0f88f5_spaceshuttle.jpeg',
    headline: "Projection mapping the NASA Space Shuttle at the Museum of Flight — a 122-foot canvas.",
    description: "The full fuselage of the Space Shuttle Trainer at Seattle's Museum of Flight became a canvas for a large-scale projection mapping narrative celebrating humanity's reach into space.",
    featured: true,
    caseStudy: true,
    challenge: "Mapping a curved, 122-foot spacecraft in a live museum environment with ambient lighting and visitor foot traffic required precise geometric calibration and a story that felt worthy of the subject matter.",
    solution: "A multi-projector array was configured using Notch's real-time 3D mapping tools, allowing for fast on-site adjustments as conditions changed. The narrative was authored as a series of acts — launch, orbit, re-entry, return — each with distinct visual language and original sound design.",
    outcome: "The event sold out within hours of announcement and generated significant press coverage. The Museum of Flight has since used the mapping as a flagship example in their event marketing.",
    technologies: ['Notch', 'Multi-projector array', 'Original sound design', '3D geometric calibration'],
  },
  {
    id: 'projection-mapped-people',
    title: "Projection Mapped People",
    client: "Self-Initiated",
    year: 2022,
    clientType: 'tech',
    category: CAT.MOTION,
    tags: ['Depth Camera', 'Projection Mapping', 'R&D'],
    heroImage: CDN + '67b77585186d5b53dfe6ad44_Screenshot%202025-02-19%20at%203.50.26%E2%80%AFPM.png',
    headline: "Depth cameras and virtual backgrounds create seamless projection-mapped effects on live performers.",
    description: "An R&D exploration using Intel RealSense depth cameras to track and project-map directly onto people in real time, creating illusions of virtual costumes and environments.",
    featured: false,
    caseStudy: true,
    challenge: null,
    solution: null,
    outcome: null,
    technologies: ['Intel RealSense', 'TouchDesigner', 'Projection mapping'],
  },
  {
    id: 'steve-aoki-paul-oakenfold',
    title: "Visuals for Steve Aoki & Paul Oakenfold",
    client: "Steve Aoki / Paul Oakenfold",
    year: 2018,
    clientType: 'music',
    category: CAT.MOTION,
    tags: ['Biometric', 'Wearable Data', 'Real-Time Visuals', 'Unreal Engine'],
    heroImage: CDN + '67b781c28ee037ada7dd2f34_1702.PNG',
    headline: "Real-time visuals driven by biometric and motion data from wearable bracelets worn by Steve Aoki and Paul Oakenfold.",
    description: "Live performance visuals that responded in real time to biometric and motion data streamed from custom wearable bracelets worn by the artists during their sets.",
    featured: false,
    caseStudy: true,
    challenge: null,
    solution: null,
    outcome: null,
    technologies: ['Custom wearable sensors', 'Unreal Engine', 'Real-time data streaming', 'Biometric processing'],
  },
  {
    id: 'childrens-hospital-donor-wall',
    title: "Children's Hospital Donor Wall",
    client: "Boston Children's Hospital",
    year: 2021,
    clientType: 'institution',
    category: CAT.INSTALLATION,
    tags: ['Interactive Display', 'Donor Recognition', 'Custom UI'],
    heroImage: CDN + '67b77e0086cac9637d9c42e4_still1.png',
    headline: "An interactive donor recognition wall prototype for Boston Children's Hospital.",
    description: "An interactive prototype for Boston Children's Hospital's donor recognition program, allowing visitors to explore stories of donors through touch and gesture.",
    featured: false,
    caseStudy: true,
    challenge: null,
    solution: null,
    outcome: null,
    technologies: ['TouchDesigner', 'Touch screen integration', 'Custom UI design'],
  },
  {
    id: 'pigeon-city-delivery',
    title: "Pigeon — City Delivery",
    client: "Self-Initiated",
    year: 2025,
    category: CAT.INSTALLATION,
    tags: ['Brand Identity', 'iOS Design', 'UI/UX', 'Conceptual'],
    heroImage: 'experiments/Pigeon/pigeons/pigeon01.png',
    headline: "A complete iOS app identity for delivering handwritten paper messages via actual pigeons — designed with complete earnestness.",
    description: "Pigeon is a conceptual iOS app concept treating urban pigeon delivery as a serious logistics product. Full brand system, logo, color palette, and interactive prototype — all built as though it were real.",
    featured: false,
    caseStudy: true,
    challenge: "Design a product that only works as a joke if the design doesn't know it's joking.",
    solution: "Treat every decision — logo, color, type, interaction — with the same rigor as a real product launch. The absurdity of the premise is the user's problem, not the designer's.",
    outcome: "A complete brand identity and three-screen iOS prototype that looks and feels like something you'd actually download.",
    technologies: ['Paper.design', 'Brand Identity', 'iOS UI Design', 'Interaction Design'],
  },
];

// Category display names
const CATEGORY_LABELS = {
  [CAT.PROJECTION]:   'Projection Mapping',
  [CAT.INSTALLATION]: 'Interactive Installations',
  [CAT.MOTION]:       'Motion & Live Visuals',
  [CAT.PERMANENT]:    'Permanent Installations',
};

// Export for use in other scripts
if (typeof module !== 'undefined') {
  module.exports = { PROJECTS, CAT, CATEGORY_LABELS };
}
